export const Theme = {
  dark: {
    primary: "bg-gray-900",
    secondary: "bg-gray-900",
    tertiary: "bg-gray-600",
    quaternary: "bg-gray-500",
    quinary: "bg-gray-400",
    senary: "bg-gray-300",
    white: "text-white",
    black: "text-black",
    background: "gray",
  },
  light: {
    primary: "bg-gray-100",
    secondary: "bg-gray-900",
    tertiary: "bg-gray-300",
    quaternary: "bg-gray-400",
    quinary: "bg-gray-500",
    senary: "bg-gray-600",
    white: "text-white",
    black: "text-black",
    background: "white",
  },
  blue: {
    primary: "bg-blue-100",
    secondary: "bg-blue-200",
    tertiary: "bg-blue-300",
    quaternary: "bg-blue-400",
    quinary: "bg-blue-500",
    senary: "bg-blue-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  blue_dark: {
    primary: "bg-blue-900",
    secondary: "bg-blue-800",
    tertiary: "bg-blue-700",
    quaternary: "bg-blue-600",
    quinary: "bg-blue-500",
    senary: "bg-blue-400",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  red: {
    primary: "bg-red-100",
    secondary: "bg-red-200",
    tertiary: "bg-red-300",
    quaternary: "bg-red-400",
    quinary: "bg-red-500",
    senary: "bg-red-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  red_dark: {
    primary: "bg-red-900",
    secondary: "bg-red-800",
    tertiary: "bg-red-700",
    quaternary: "bg-red-600",
    quinary: "bg-red-500",
    senary: "bg-red-400",
    white: "text-white",

    background: "white",
  },
  green: {
    primary: "bg-green-100",
    secondary: "bg-green-200",
    tertiary: "bg-green-300",
    quaternary: "bg-green-400",
    quinary: "bg-green-500",
    senary: "bg-green-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  green_dark: {
    primary: "bg-green-900",
    secondary: "bg-green-800",
    tertiary: "bg-green-700",
    quaternary: "bg-green-600",
    quinary: "bg-green-500",
    senary: "bg-green-400",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  yellow: {
    primary: "bg-yellow-100",
    secondary: "bg-yellow-200",
    tertiary: "bg-yellow-300",
    quaternary: "bg-yellow-400",
    quinary: "bg-yellow-500",
    senary: "bg-yellow-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  yellow_dark: {
    primary: "bg-yellow-900",
    secondary: "bg-yellow-800",
    tertiary: "bg-yellow-700",
    quaternary: "bg-yellow-600",
    quinary: "bg-yellow-500",
    senary: "bg-yellow-400",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  orange: {
    primary: "bg-orange-100",
    secondary: "bg-orange-200",
    tertiary: "bg-orange-300",
    quaternary: "bg-orange-400",
    quinary: "bg-orange-500",
    senary: "bg-orange-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  orange_dark: {
    primary: "bg-orange-900",
    secondary: "bg-orange-800",
    tertiary: "bg-orange-700",
    quaternary: "bg-orange-600",
    quinary: "bg-orange-500",
    senary: "bg-orange-400",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  purple: {
    primary: "bg-purple-100",
    secondary: "bg-purple-200",
    tertiary: "bg-purple-300",
    quaternary: "bg-purple-400",
    quinary: "bg-purple-500",
    senary: "bg-purple-600",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
  purple_dark: {
    primary: "bg-purple-900",
    secondary: "bg-purple-800",
    tertiary: "bg-purple-700",
    quaternary: "bg-purple-600",
    quinary: "bg-purple-500",
    senary: "bg-purple-400",
    white: "text-white",
    black: "text-black",

    background: "white",
  },
};
